import type { PropertyProfile } from './types.js';

/**
 * The three launch properties, per the Product Build Brief (section 02).
 * Coordinates are approximate town-centre positions; refine during onboarding.
 */
export const PROPERTIES: PropertyProfile[] = [
  {
    id: 'ten-fifty-bakers',
    name: 'Ten Fifty Bakers',
    locality: 'Bakers Beach',
    lat: -41.24,
    lon: 146.63,
    inventory: 'whole-property',
    maxGuests: 10,
    minStay: 2,
    adultsOnly: false,
    guestFit: {
      'nature-walking': 1.0,
      wellness: 1.0,
      romantic: 0.95,
      'wedding-milestone': 0.9,
      family: 0.8,
      'school-holiday': 0.8,
      'long-weekend': 0.85,
      'public-holiday': 0.7,
      festival: 0.5,
      'food-wine': 0.6,
      arts: 0.5,
      sports: 0.45,
      music: 0.4,
      community: 0.3,
      market: 0.25,
      conference: 0.15,
      business: 0.1,
      cruise: 0.2,
    },
    cautionTags: ['conference', 'business', 'cruise', 'music'],
    cautionNote:
      'Do not automatically target short city events, late-night events or one-night overflow demand — distance and the remote experience can outweigh raw attendance.',
  },
  {
    id: 'prescription-pad',
    name: 'The Prescription Pad',
    locality: 'Shearwater',
    lat: -41.157,
    lon: 146.542,
    inventory: 'whole-property',
    maxGuests: 10,
    minStay: 2,
    adultsOnly: false,
    guestFit: {
      family: 1.0,
      'school-holiday': 1.0,
      'wedding-milestone': 0.95,
      sports: 0.9,
      'long-weekend': 0.9,
      community: 0.7,
      'public-holiday': 0.7,
      festival: 0.65,
      music: 0.6,
      'food-wine': 0.6,
      market: 0.5,
      'nature-walking': 0.55,
      wellness: 0.5,
      arts: 0.5,
      conference: 0.4,
      business: 0.35,
      cruise: 0.35,
      romantic: 0.15,
    },
    cautionTags: ['romantic'],
    cautionNote:
      'Weak fit for solo travellers and most couples — campaigns must justify booking an entire large house and respect seasonal minimum stays.',
  },
  {
    id: 'annie-may',
    name: 'Annie May',
    locality: 'Devonport',
    lat: -41.18,
    lon: 146.36,
    inventory: 'room-level',
    maxGuests: 2, // per room; 7 separately bookable ensuite rooms
    minStay: 1,
    adultsOnly: true,
    guestFit: {
      conference: 1.0,
      business: 1.0,
      cruise: 0.95, // Spirit of Tasmania stopovers
      funeral: 0.9, // family travelling for Devonport funerals; quiet, adults-only rooms
      romantic: 0.9,
      'wedding-milestone': 0.85,
      arts: 0.8,
      music: 0.75,
      'food-wine': 0.8,
      festival: 0.7,
      sports: 0.6,
      market: 0.55,
      community: 0.5,
      'public-holiday': 0.6,
      'long-weekend': 0.7,
      'nature-walking': 0.55,
      wellness: 0.6,
      family: 0.05,
      'school-holiday': 0.1,
    },
    cautionTags: ['family', 'school-holiday'],
    cautionNote:
      'Adults-only: never send family-with-children campaigns. Score and market room inventory — the building is not one bookable unit.',
  },
];
